In [16]:
import numpy as np

import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [2]:
sent=['the glass of milk', 'the glass of juice', 'the cup of tea',
    'I am a good boy', 'I am a good developer', 'understand the meaning of words', 'your blogs are good',]

In [3]:
voc_size = 10000 # 
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[6180, 2630, 4299, 8886],
 [6180, 2630, 4299, 8150],
 [6180, 8434, 4299, 1800],
 [5010, 9155, 2446, 8007, 6740],
 [5010, 9155, 2446, 8007, 9419],
 [3787, 6180, 675, 4299, 8652],
 [2434, 3086, 3254, 8007]]

In [ ]:
# Padding docs to create equal length vectors
sent_len = 8
padded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_len)
padded_docs

array([[   0,    0,    0,    0, 6180, 2630, 4299, 8886],
       [   0,    0,    0,    0, 6180, 2630, 4299, 8150],
       [   0,    0,    0,    0, 6180, 8434, 4299, 1800],
       [   0,    0,    0, 5010, 9155, 2446, 8007, 6740],
       [   0,    0,    0, 5010, 9155, 2446, 8007, 9419],
       [   0,    0,    0, 3787, 6180,  675, 4299, 8652],
       [   0,    0,    0,    0, 2434, 3086, 3254, 8007]])

In [7]:
dim = 10

In [10]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_len))
model.compile(optimizer='adam', loss='mse')

In [13]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.predict(padded_docs) # Each word will be represented by vector of length 10 as set in dim

1/1 [==============================] - 2s 2s/step


array([[[ 3.4858931e-02, -1.8898137e-03, -2.3567760e-02,  4.9954999e-02,
          2.2828568e-02,  2.6423562e-02, -4.7011938e-02, -3.3705462e-02,
         -2.3224641e-02,  2.6519272e-02],
        [ 3.4858931e-02, -1.8898137e-03, -2.3567760e-02,  4.9954999e-02,
          2.2828568e-02,  2.6423562e-02, -4.7011938e-02, -3.3705462e-02,
         -2.3224641e-02,  2.6519272e-02],
        [ 3.4858931e-02, -1.8898137e-03, -2.3567760e-02,  4.9954999e-02,
          2.2828568e-02,  2.6423562e-02, -4.7011938e-02, -3.3705462e-02,
         -2.3224641e-02,  2.6519272e-02],
        [ 3.4858931e-02, -1.8898137e-03, -2.3567760e-02,  4.9954999e-02,
          2.2828568e-02,  2.6423562e-02, -4.7011938e-02, -3.3705462e-02,
         -2.3224641e-02,  2.6519272e-02],
        [ 1.3367955e-02,  3.2943312e-02, -4.0053379e-02,  1.9811396e-02,
          4.8655655e-02,  1.2235809e-02,  1.7972659e-02,  2.9436324e-02,
          4.8949089e-02,  1.4820341e-02],
        [ 8.6685270e-04,  2.4009679e-02,  8.5837841e-03, -4.

In [15]:
model.predict(padded_docs[0])

1/1 [==============================] - 0s 37ms/step


array([[ 0.03485893, -0.00188981, -0.02356776,  0.049955  ,  0.02282857,
         0.02642356, -0.04701194, -0.03370546, -0.02322464,  0.02651927],
       [ 0.03485893, -0.00188981, -0.02356776,  0.049955  ,  0.02282857,
         0.02642356, -0.04701194, -0.03370546, -0.02322464,  0.02651927],
       [ 0.03485893, -0.00188981, -0.02356776,  0.049955  ,  0.02282857,
         0.02642356, -0.04701194, -0.03370546, -0.02322464,  0.02651927],
       [ 0.03485893, -0.00188981, -0.02356776,  0.049955  ,  0.02282857,
         0.02642356, -0.04701194, -0.03370546, -0.02322464,  0.02651927],
       [ 0.01336795,  0.03294331, -0.04005338,  0.0198114 ,  0.04865566,
         0.01223581,  0.01797266,  0.02943632,  0.04894909,  0.01482034],
       [ 0.00086685,  0.02400968,  0.00858378, -0.04526167, -0.01433051,
         0.03583957,  0.01498799,  0.03025613,  0.03249259, -0.02350837],
       [-0.03989274, -0.04749446,  0.03978963,  0.00730459, -0.00560479,
        -0.02136123,  0.00474136,  0.0066501 

### 2. Modelling

In [17]:
from tensorflow.keras.datasets import imdb

In [18]:
max_features = 10000 # vocabulary size
(Xtrain, ytrain), (Xtest, ytest) = imdb.load_data(num_words=max_features)

17464789/17464789 [==============================] - 4s 0us/step


In [19]:
print(f'Train size - {Xtrain.shape}, Train labels shape - {ytrain.shape}')
print(f'Test size - {Xtest.shape}, Test labels shape - {ytest.shape}')

Train size - (25000,), Train labels shape - (25000,)
Test size - (25000,), Test labels shape - (25000,)


In [ ]:
len(Xtrain), len(Xtrain[0]), len(Xtrain[1]) # Thus, one hot encoded vectors of each sentences

(218, 25000, 189)

In [26]:
sample_review, sample_label = Xtrain[0], ytrain[0]
print(sample_review, '\n', sample_label)

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32] 
 1


In [27]:
## Mapping of words to indexes
word_index = imdb.get_word_index()
word_index

1641221/1641221 [==============================] - 0s 0us/step


{'fawn': 34701,
 'tsukino': 52006,
 'nunnery': 52007,
 'sonja': 16816,
 'vani': 63951,
 'woods': 1408,
 'spiders': 16115,
 'hanging': 2345,
 'woody': 2289,
 'trawling': 52008,
 "hold's": 52009,
 'comically': 11307,
 'localized': 40830,
 'disobeying': 30568,
 "'royale": 52010,
 "harpo's": 40831,
 'canet': 52011,
 'aileen': 19313,
 'acurately': 52012,
 "diplomat's": 52013,
 'rickman': 25242,
 'arranged': 6746,
 'rumbustious': 52014,
 'familiarness': 52015,
 "spider'": 52016,
 'hahahah': 68804,
 "wood'": 52017,
 'transvestism': 40833,
 "hangin'": 34702,
 'bringing': 2338,
 'seamier': 40834,
 'wooded': 34703,
 'bravora': 52018,
 'grueling': 16817,
 'wooden': 1636,
 'wednesday': 16818,
 "'prix": 52019,
 'altagracia': 34704,
 'circuitry': 52020,
 'crotch': 11585,
 'busybody': 57766,
 "tart'n'tangy": 52021,
 'burgade': 14129,
 'thrace': 52023,
 "tom's": 11038,
 'snuggles': 52025,
 'francesco': 29114,
 'complainers': 52027,
 'templarios': 52125,
 '272': 40835,
 '273': 52028,
 'zaniacs': 52130,

In [30]:
word_index_reversed = {value:key for key, value in word_index.items()}
word_index_reversed[1]

'the'

In [36]:
decoded_review = ' '.join([word_index_reversed.get(i-3, '?') for i in sample_review])
decoded_review

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly fishing was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little boy's that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big profile for the whole film but these children are amazing and should be praised for what they have done don't you th

In [37]:
max_len = 500
Xtrain = pad_sequences(Xtrain, maxlen=max_len, padding='pre')
Xtest = pad_sequences(Xtest, maxlen=max_len, padding='pre')

In [38]:
Xtrain[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [46]:
## RNN Architecture
model = Sequential()
model.add(Embedding(max_features, 128, input_length=max_len))
model.add(SimpleRNN(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 500, 128)          1280000   
                                                                 
 simple_rnn_1 (SimpleRNN)    (None, 128)               32896     
                                                                 
 dense_1 (Dense)             (None, 1)                 129       
                                                                 
Total params: 1313025 (5.01 MB)
Trainable params: 1313025 (5.01 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [47]:
## Create an instance of EarlyStopping Callback
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
early_stopping

In [49]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(Xtrain, ytrain, epochs=10, batch_size=32, validation_split=0.2, callbacks=[early_stopping])

Epoch 1/10
625/625 [==============================] - 86s 136ms/step - loss: 0.7399 - accuracy: 0.6231 - val_loss: 0.5386 - val_accuracy: 0.7090
Epoch 2/10
625/625 [==============================] - 80s 129ms/step - loss: 3.3362 - accuracy: 0.6923 - val_loss: 257810.0781 - val_accuracy: 0.7358
Epoch 3/10
625/625 [==============================] - 78s 124ms/step - loss: 0.4256 - accuracy: 0.8094 - val_loss: 0.4514 - val_accuracy: 0.7874
Epoch 4/10
625/625 [==============================] - 102s 164ms/step - loss: 0.2976 - accuracy: 0.8779 - val_loss: 0.3942 - val_accuracy: 0.8410
Epoch 5/10
625/625 [==============================] - 81s 130ms/step - loss: 0.2207 - accuracy: 0.9140 - val_loss: 0.4264 - val_accuracy: 0.8134
Epoch 6/10
625/625 [==============================] - 69s 110ms/step - loss: 0.1703 - accuracy: 0.9358 - val_loss: 0.4928 - val_accuracy: 0.8334
Epoch 7/10
625/625 [==============================] - 68s 110ms/step - loss: 3.7440 - accuracy: 0.7691 - val_loss: 0.6924 - 

In [50]:
model.save('rnn_imdb.h5')

d:\Programs\Anaconda\envs\gen_env\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
